### ISSUE TITLE
MK3_FAST_LCD Feedback

### ISSUE THREAD

**Issue by leptun** [leptun/Prusa-Firmware#1]
This is the place to write all feedback and changes wanted for this fork

**Comment by wavexx** [comment]
As written there:  I would really avoid putting the lcd isr in timer1. At low speeds with LA any delay will kill advance steps, on fast moves when dual/quad stepping kicks-in the timing gets really tight. And it's not like serial I/O that needs to drain a buffer quickly.

This might work for now, but one thing I'd like to investigate is to raise the frequency before dual/quad stepping kicks in (right now it's 10/20khz) to improve the quality of fast moves. For example, grid infill *should* look a better (and I'm referring at the quality of the extrusion for strength purposes really - not at the look of it). There's very little time available already when doing a move at 150mm/s. This is also indirectly triggered by a rectraction+wipe if you have a geared extruder.

I think timer2 would be a better candidate for this. I'm not sure at which frequency it currently ticks exactly as I'm away from work, but if I'm not mistaken this was used for the burn-your-cap style bed heating..

**Comment by leptun** [comment]
Yes, timer2 is the only other timer that is free or can be sped up. The only problem with using it is loosing “use system timer 2” completely. Also the timer2 library should be removed entirely if the change is made. (Prusa might not want this. Maybe they have plans using it in the future since they said they hope to implement a fix to clicking bed in 3.8.0. Idk.🤷‍♂️Hope they don’t use it)

Did you have time to test the firmware as is?

I also agree with you that at high speed grid infill has small gaps at the begining/end of extrusion. The real kicker for me is running the infill at 300mm/s with higher acceleration. The problems appear somewhere at the “middle” of the line and manifests itself by an instantaneous stop and start of the motion. Maybe the lcd was to blame since it was updating the status screen.

**Comment by leptun** [comment]
Wait. I might be mestaken on what timers can be used. I think there is at least another timer that can be used. It is one that can output to one of the heater outputs and if I’m not mistaken it is controlled through software, not timer comparison. I have to check this when I’m at a computer.

**Comment by leptun** [comment]
I’m moving the ISR to timer3. I’m also changing it so that the lcd_isr() behaves just like the stepper interrupt, using OCR3A to set the interrupt to trigger at the correct delay.

I am gone for the day, will implement this and post at ~20:00EDT

**Comment by leptun** [comment]
Updated as mentioned above.

**Comment by wavexx** [comment]
Didn't have a chance this week to have a good look at this, sorry for not commenting sooner.
I'll be away for the next few days

**Comment by leptun** [comment]
No problem. Starting a new branch with the changes and doing a PR. Tested it, moddified it and can finally say it works

**Comment by leptun** [comment]
The discussion will move to that PR
