### ISSUE TITLE
[BUG] Arduino render--> error 'PC_PREHEAT_HOTEND_TEMP' was not declared in this scope

### ISSUE THREAD

**Issue by 3Dietrich** [leptun/Prusa-Firmware#4]
**Printer type** - [e.g. MK3S, MK3, MK2.5S, MK2.5, MK2S, MK2]
no printer yet, just Arduino 1.8.13 on macOS 15.15, checked out MK3_GCC

no printer yet, no MMU, no Octoprint

**Describe the bug**
I checked out MK3_GCC, 
added Configuration_prusa.h
changed config.h (LANG_MODE 0)
and opened Firmware.ino in Arduino 1.8.13 and pressed "verify"

beside (obviously not important error): Error while detecting libraries included by /var/folders/vd/w24gbgk53p54d2r9nb3xr7580000gn/T/arduino_build_602577/sketch/ultralcd.cpp
it ended red starting with 
```
/var/folders/vd/w24gbgk53p54d2r9nb3xr7580000gn/T/arduino_build_602577/sketch/ultralcd.cpp: In function 'void mFilamentItem_PC()':
ultralcd.cpp:2501:19: error: 'PC_PREHEAT_HOTEND_TEMP' was not declared in this scope
     mFilamentItem(PC_PREHEAT_HOTEND_TEMP, PC_PREHEAT_HPB_TEMP);
```
full copy of verify output: [verify_error.txt](https://github.com/leptun/Prusa-Firmware/files/4976298/verify_error.txt)

**To Reproduce**
see 'Describe the bug'  
**Expected behavior**
it should render the firmware without errors

**Comment by leptun** [comment]
Did you use the provided default Configuration_prusa.h files in the variants folder?
You are missing one of the hardcoded values for preheating for the new PC filament. You could add the required defines to your modified file manually.

**Comment by leptun** [comment]
These are the two lines that are probably missing in your Configuration_prusa.h file:
```
#define PC_PREHEAT_HOTEND_TEMP 275
#define PC_PREHEAT_HPB_TEMP 110
```

**Comment by 3Dietrich** [comment]
> Did you use the provided default Configuration_prusa.h files in the variants folder?

Yes. I couldn't find one in your system, so I took what I already had.
> You are missing one of the hardcoded values for preheating for the new PC filament. You could add the required 
defines to your modified file manually.

Yea! cool! thank you, that worked!
